// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: common_data.proto

package proto_define

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kingdom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items []string `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Kingdom) Reset() {
	*x = Kingdom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kingdom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kingdom) ProtoMessage() {}

func (x *Kingdom) ProtoReflect() protoreflect.Message {
	mi := &file_common_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kingdom.ProtoReflect.Descriptor instead.
func (*Kingdom) Descriptor() ([]byte, []int) {
	return file_common_data_proto_rawDescGZIP(), []int{0}
}

func (x *Kingdom) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Kingdom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kingdom) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type FailMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int64  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Desc      string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *FailMessage) Reset() {
	*x = FailMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailMessage) ProtoMessage() {}

func (x *FailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailMessage.ProtoReflect.Descriptor instead.
func (*FailMessage) Descriptor() ([]byte, []int) {
	return file_common_data_proto_rawDescGZIP(), []int{1}
}

func (x *FailMessage) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *FailMessage) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_common_data_proto protoreflect.FileDescriptor

var file_common_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x73, 0x32, 0x76, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x22,
	0x43, 0x0a, 0x07, 0x4b, 0x69, 0x6e, 0x67, 0x64, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x40, 0x0a, 0x0b, 0x46, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x42, 0x5f, 0x0a, 0x1c, 0x67, 0x73, 0x32, 0x76, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5a, 0x20, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0xaa, 0x02, 0x1c, 0x47, 0x73, 0x32, 0x76, 0x73,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_data_proto_rawDescOnce sync.Once
	file_common_data_proto_rawDescData = file_common_data_proto_rawDesc
)

func file_common_data_proto_rawDescGZIP() []byte {
	file_common_data_proto_rawDescOnce.Do(func() {
		file_common_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_data_proto_rawDescData)
	})
	return file_common_data_proto_rawDescData
}

var file_common_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_data_proto_goTypes = []any{
	(*Kingdom)(nil),     // 0: gs2vs.game.Kingdom
	(*FailMessage)(nil), // 1: gs2vs.game.FailMessage
}
var file_common_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_data_proto_init() }
func file_common_data_proto_init() {
	if File_common_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Kingdom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FailMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_data_proto_goTypes,
		DependencyIndexes: file_common_data_proto_depIdxs,
		MessageInfos:      file_common_data_proto_msgTypes,
	}.Build()
	File_common_data_proto = out.File
	file_common_data_proto_rawDesc = nil
	file_common_data_proto_goTypes = nil
	file_common_data_proto_depIdxs = nil
}
